% ----------------------------------
\documentclass{article} %
\usepackage{Sweave}
\usepackage{subfig}
\usepackage{graphicx}
\usepackage[margin=0.2in, paperwidth=11in, paperheight=17in]{geometry}
\SweaveOpts{echo=FALSE}

<<echo=false,results=hide>>=
source("report-pdf.R")
@

\newcommand\report[1]{

  \begin{figure}
    \subfloat[Natural Gas]{\label{fig:gas}\includegraphics[width=2in]{reports/drawSupplyDemandForMarketBySubstanceNatural_Gas_#1.pdf}}
    \caption{Markets}
  \end{figure}
  
  \begin{figure}
    \subfloat[Segment 1]{\label{fig:esm1}\includegraphics[width=2in]{reports/drawSupplyDemandForMarketSegment1_#1.pdf}}
    \subfloat[Segment 2]{\label{fig:esm2}\includegraphics[width=2in]{reports/drawSupplyDemandForMarketSegment2_#1.pdf}}
    \subfloat[Segment 3]{\label{fig:esm3}\includegraphics[width=2in]{reports/drawSupplyDemandForMarketSegment3_#1.pdf}}
    \subfloat[Segment 4]{\label{fig:esm4}\includegraphics[width=2in]{reports/drawSupplyDemandForMarketSegment4_#1.pdf}}
    \subfloat[Segment 5]{\label{fig:esm5}\includegraphics[width=2in]{reports/drawSupplyDemandForMarketSegment5_#1.pdf}}
    \caption{Electricity Spot Market}
  \end{figure}
  
  \clearpage 
}

\begin{document}

<<results=tex>>=
createReportPdf <- function(tick) {
  for (segment in 1:5) {
    drawSupplyDemandForMarketSegment("ElectricitySpotMarket",segment,tick)
  }
  drawSupplyDemandForMarketBySubstance("CommodityMarket","Natural Gas",tick)
  cat("\\report{",tick,"}\n",sep="")
}

runSimulation(createReportPdf,30)
@

\end{document}
